package com.oms.supplychain.service.warehouse.impl;

import com.oms.supplychain.service.warehouse.PurchaseGoodsClient;
import com.oms.common.api.RemoteInventoryService;
import com.oms.common.model.entity.GoodsSkuSnInfo;
import com.oms.common.model.entity.wms.WmsInventoryBatch;
import com.oms.common.model.dto.wms.WmsInventoryBatchDto;
import com.oms.supplychain.model.dto.warehouse.SimulationStoreInfoDto;
import com.ruoyi.common.core.domain.R;
import com.ruoyi.common.core.web.page.TableDataInfo;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.dao.DuplicateKeyException;
import javax.annotation.Resource;
import java.math.*;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

/** Purchase plans are immutable after approval; receipts consume the remaining planned quantity.
 * Existing purchase/receipt/ticket rows serialize transitions, in that order.
 * Inventory receives use stable document keys across retries.
 * Only valid workflow states may advance; inventory operations remain idempotent. */
@Service
public class PurchaseWorkspaceService {
    @Resource private JdbcTemplate jdbc;
    @Resource @org.springframework.context.annotation.Lazy private com.oms.supplychain.service.wms.WmsInboundService wms;
    @Resource private WarehouseWorkspaceService warehouses;
    @Resource private PurchaseGoodsClient goods;
    @Resource private RemoteInventoryService inventory;
    @Resource private org.springframework.transaction.PlatformTransactionManager transactionManager;

    private static void require(boolean ok,String message){if(!ok)throw new IllegalArgumentException(message);}
    private String company(String c){require(c!=null&&!c.trim().isEmpty(),"请先选择公司");return c.trim().toUpperCase(Locale.ROOT);}
    private static String text(Object v){return v==null?"":v.toString().trim();}
    private static int integer(Object v){try{return new BigDecimal(text(v)).intValueExact();}catch(Exception e){throw new IllegalArgumentException("数量或状态必须为整数");}}
    private static long id(Object v){try{return Long.parseLong(text(v));}catch(Exception e){throw new IllegalArgumentException("无效记录编号");}}
    private static BigDecimal money(Object v){try{BigDecimal n=new BigDecimal(text(v)).setScale(2,RoundingMode.UNNECESSARY);require(n.signum()>=0&&n.precision()<=15,"单价必须为非负金额且最多两位小数");return n;}catch(ArithmeticException|NumberFormatException e){throw new IllegalArgumentException("单价格式不正确，最多两位小数");}}
    private static String required(Map<String,Object> row,String key,String label,int max){String v=text(row.get(key));require(!v.isEmpty()&&v.length()<=max,label+"不能为空且不能超过 "+max+" 字");return v;}
    private static Map<String,Object> map(Object... values){Map<String,Object> r=new LinkedHashMap<>();for(int i=0;i<values.length;i+=2)r.put((String)values[i],values[i+1]);return r;}
    private Map<String,Object> camel(Map<String,Object> row){Map<String,Object> out=new LinkedHashMap<>();row.forEach((k,v)->{StringBuilder b=new StringBuilder();boolean up=false;for(char c:k.toCharArray()){if(c=='_'){up=true;continue;}b.append(up?Character.toUpperCase(c):c);up=false;}out.put(b.toString(),v);});return out;}
    private List<Map<String,Object>> rows(String sql,Object... args){return jdbc.queryForList(sql,args).stream().map(this::camel).map(this::purchasePresentation).map(com.oms.supplychain.service.wms.TicketPresentation::present).collect(Collectors.toList());}
    /** List, detail and export use the same workflow state; workflow states determine available actions. */
    private Map<String,Object> purchasePresentation(Map<String,Object> row){
        if(!row.containsKey("poState")||!row.containsKey("receiptCount"))return row;
        int state=integer(row.get("poState")),receipts=integer(row.get("receiptCount"));
        String[] states={"状态异常","草稿","待收货","收货中","已完成","已关闭"};
        row.put("stateLabel",state==-1?"已作废":state>=1&&state<states.length?states[state]:"状态异常");
        row.put("editable",state==1&&receipts==0);
        row.put("editBlockReason",receipts>0?"已关联 "+receipts+" 张到货单，采购计划已锁定，请查看关联到货单。":state!=1?"当前单据"+row.get("stateLabel")+"，采购计划不可编辑。":"");
        String note="";
        if(state==1)note=receipts>0?"草稿已关联到货单，状态与流程规则不一致，请核对关联单据；暂不可编辑或审核。":"下一步：完善采购明细并审核采购；审核后才能创建到货单。";
        else if(state==2||state==3)note="下一步：按剩余数量创建到货单，审核到货单后完成收货及库存入账；采购进度按成功入账数量更新。";
        else note="采购流程已结束，可查看关联到货单和库存入账结果。";
        row.put("stateNotice",note);
        row.put("stateNeedsReview",state==1&&receipts>0);
        return row;
    }
    private long count(String sql,Object... args){return jdbc.queryForObject(sql,Long.class,args);}
    private TransactionTemplate transaction(){
        TransactionTemplate tx=new TransactionTemplate(transactionManager);
        tx.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);
        return tx;
    }
    private Map<String,Object> lockRow(String c,String kind,long key,boolean exclusive){
        List<Map<String,Object>> found=rows("SELECT * FROM "+table(kind)+" WHERE id=? AND UPPER(company_code)=?"+(exclusive?" FOR UPDATE":" LOCK IN SHARE MODE"),key,c);
        require(found.size()==1,"记录不存在或不属于当前公司");return found.get(0);
    }
    /** No company mutex: all mutations of one purchase chain follow the same lock order. */
    private Map<String,Object> lockDocument(String c,String kind,long key){
        if(kind.equals("supplier")||kind.equals("purchase"))return lockRow(c,kind,key,true);
        Map<String,Object> row=one(c,kind,key);
        String poSn=text(row.get(kind.equals("receipt")?"poSn":"originalSn"));
        Map<String,Object> purchase=byCode(c,"purchase","po_sn",poSn);
        lockRow(c,"purchase",id(purchase.get("id")),true);
        if(kind.equals("ticket")){
            Map<String,Object> receipt=byCode(c,"receipt","no_sn",text(row.get("relationSn")));
            require(poSn.equals(text(receipt.get("poSn"))),"入库单与到货单的采购来源不一致，请核对");
            lockRow(c,"receipt",id(receipt.get("id")),true);
        }
        return lockRow(c,kind,key,true);
    }
    private Map<String,Object> supplierForReference(String c,String sn){
        Map<String,Object> supplier=byCode(c,"supplier","supplier_sn",sn);
        return lockRow(c,"supplier",id(supplier.get("id")),false);
    }
    private String table(String kind){switch(kind){case "supplier":return "supplier_info";case "purchase":return "po_info";case "receipt":return "no_tickets";case "ticket":return "wms_tickets";default:throw new IllegalArgumentException("未知单据类型");}}
    private String code(String kind){return kind.equals("supplier")?"supplierSn":kind.equals("purchase")?"poSn":kind.equals("receipt")?"noSn":"sn";}
    private Map<String,Object> one(String c,String kind,long key){List<Map<String,Object>> found=rows("SELECT * FROM "+table(kind)+" WHERE UPPER(company_code)=? AND id=?",c,key);require(found.size()==1,"记录不存在或不属于当前公司");return found.get(0);}
    private Map<String,Object> byCode(String c,String kind,String column,String value){List<Map<String,Object>> r=rows("SELECT * FROM "+table(kind)+" WHERE UPPER(company_code)=? AND "+column+"=?",c,value);require(r.size()==1,"关联单据不存在或编码重复，请核对资料");return r.get(0);}
    private String sn(String prefix){return prefix+UUID.randomUUID().toString().replace("-","");}
    private long insert(String table,Map<String,Object> fields){GeneratedKeyHolder holder=new GeneratedKeyHolder();String sql="INSERT INTO "+table+"("+String.join(",",fields.keySet())+") VALUES("+String.join(",",Collections.nCopies(fields.size(),"?"))+")";try{jdbc.update(conn->{PreparedStatement s=conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);int i=1;for(Object v:fields.values())s.setObject(i++,v);return s;},holder);return holder.getKey().longValue();}catch(DuplicateKeyException e){throw new IllegalArgumentException("编码、名称或单据关联已存在，请刷新后重试");}}
    private void event(String c,String sn,String action,String user,String message){insert("purchase_event",map("company_code",c,"document_sn",sn,"action",action,"operator",user,"message",message.length()>1000?message.substring(0,1000):message));}
    private String joins(String alias){return " LEFT JOIN wms_simulation_store_info v ON v.wms_simulation_code="+alias+".wms_simulation_code AND UPPER(v.company_code)=UPPER("+alias+".company_code) LEFT JOIN owner_warehouse ow ON ow.id=v.owner_warehouse_id AND UPPER(ow.company_code)=UPPER(v.company_code) LEFT JOIN owner_info o ON o.id=ow.owner_id AND UPPER(o.company_code)=UPPER(ow.company_code) LEFT JOIN wms_real_store_info w ON w.id=ow.real_store_id AND UPPER(w.company_code)=UPPER(ow.company_code)";}
    private String warehouseColumns(){return ",v.wms_simulation_name warehouse_name,o.owner_name,w.wms_name real_warehouse_name";}
    private String base(String kind){
        if(kind.equals("supplier"))return "SELECT s.*,(SELECT COUNT(*) FROM po_info p WHERE UPPER(p.company_code)=UPPER(s.company_code) AND p.supplier_sn=s.supplier_sn AND p.po_state IN(1,2,3)) open_count FROM supplier_info s";
        if(kind.equals("purchase"))return "SELECT p.*,s.supplier_name,GREATEST(p.number_expected-p.number_actually,0) remaining_quantity,(SELECT COUNT(*) FROM no_tickets n WHERE UPPER(n.company_code)=UPPER(p.company_code) AND n.po_sn=p.po_sn) receipt_count"+warehouseColumns()+" FROM po_info p LEFT JOIN supplier_info s ON s.supplier_sn=p.supplier_sn AND UPPER(s.company_code)=UPPER(p.company_code)"+joins("p");
        if(kind.equals("receipt"))return "SELECT n.*,CASE WHEN n.relation_sn IS NOT NULL AND n.relation_sn<>'' THEN (SELECT t.actual_warehouse FROM wms_tickets t WHERE t.sn=n.relation_sn AND UPPER(t.company_code)=UPPER(n.company_code)) ELSE v.inbound_mode END actual_warehouse"+warehouseColumns()+" FROM no_tickets n"+joins("n");
        if(kind.equals("ticket")) {
            String source="SELECT t.*"+warehouseColumns()+",o.id owner_id,w.id real_store_id,a.dispatch_state,a.receipt_state,c.provider,a.external_order,a.warehouse_status,a.last_query_result,a.last_query_time,a.query_message,a.last_error,a.cancel_reason,"
                +"CASE WHEN t.actual_warehouse=1 THEN a.receipt_state='COMPLETE' ELSE t.status_ticket=2 END receipt_final,"
                +"COALESCE(q.planned,0) number_expected,COALESCE(q.received,0) number_actually,CASE WHEN t.actual_warehouse=1 THEN COALESCE(r.posted,0) ELSE COALESCE(q.posted,0) END number_posted,"
                +"GREATEST(t.modify_time,COALESCE(a.modify_time,t.modify_time),COALESCE(q.updated,t.modify_time)) business_updated_time "
                +"FROM wms_tickets t"+joins("t")
                +" LEFT JOIN wms_inbound_task a ON a.ticket_id=t.id AND a.company_code=UPPER(t.company_code) LEFT JOIN wms_connection c ON c.id=a.connection_id AND c.company_code=a.company_code"
                +" LEFT JOIN (SELECT UPPER(company_code) company_code,sn,SUM(number_expected) planned,SUM(number_actually) received,SUM(CASE WHEN inventory_is_handle=2 THEN number_actually ELSE 0 END) posted,MAX(modify_time) updated FROM wms_tickets_goods GROUP BY UPPER(company_code),sn) q ON q.sn=t.sn AND q.company_code=UPPER(t.company_code)"
                +" LEFT JOIN (SELECT company_code,task_id,SUM(CASE WHEN posted=1 THEN good_qty+bad_qty ELSE 0 END) posted FROM wms_receipt_line GROUP BY company_code,task_id) r ON r.task_id=a.id AND r.company_code=a.company_code";
            return com.oms.supplychain.service.wms.TicketPresentation.enrich(source);
        }
        if(kind.equals("line"))return "SELECT z.*,CASE WHEN z.status_ticket=5 THEN 'NONE' WHEN z.inventory_is_handle=3 THEN 'ERROR' WHEN z.number_posted=z.number_actually AND (z.number_posted>0 OR z.receipt_final=1 AND z.inventory_is_handle=2) THEN 'POSTED' WHEN z.number_posted>0 THEN 'PARTIAL' ELSE 'NOT_STARTED' END posting_state FROM (SELECT g.*,t.ticket_type,t.original_sn,t.relation_sn,t.wms_simulation_code,t.status_ticket,t.inventory_status,t.actual_warehouse,t.owner_name,t.warehouse_name,t.real_warehouse_name,t.owner_id,t.real_store_id,t.dispatch_state,t.receipt_state,t.provider,t.external_order,t.warehouse_status,t.progress,t.receipt_final,t.short_quantity,t.business_updated_time,CASE WHEN t.actual_warehouse=1 THEN COALESCE((SELECT SUM(r.good_qty+r.bad_qty) FROM wms_receipt_line r WHERE r.ticket_line_id=g.id AND r.company_code=UPPER(g.company_code) AND r.posted=1),0) ELSE CASE WHEN g.inventory_is_handle=2 THEN g.number_actually ELSE 0 END END number_posted FROM wms_tickets_goods g JOIN ("+base("ticket")+") t ON t.sn=g.sn AND UPPER(t.company_code)=UPPER(g.company_code)) z";
        throw new IllegalArgumentException("未知列表类型");
    }
    private String filter(String kind,Map<String,Object> q,List<Object> args){StringBuilder w=new StringBuilder();Map<String,String> allowed=new LinkedHashMap<>();
        if(kind.equals("supplier")){allowed.put("keyword","supplier_name");allowed.put("supplierSn","supplier_sn");allowed.put("companyName","company_name");allowed.put("status","status");}
        if(kind.equals("purchase")){allowed.put("keyword","po_name");allowed.put("poSn","po_sn");allowed.put("supplierSn","supplier_sn");allowed.put("state","po_state");}
        if(kind.equals("receipt")){allowed.put("poSn","po_sn");allowed.put("noSn","no_sn");allowed.put("state","no_state");}
        if(kind.equals("ticket")||kind.equals("line")){allowed.put("postingState","posting_state");allowed.put("progress","progress");allowed.put("ownerId","owner_id");allowed.put("realStoreId","real_store_id");allowed.put("actualWarehouse","actual_warehouse");allowed.put("provider","provider");allowed.put("externalOrder","external_order");allowed.put("sn","sn");allowed.put("poSn","original_sn");allowed.put("noSn","relation_sn");allowed.put("state","status_ticket");allowed.put("ticketType","ticket_type");allowed.put("inventoryStatus",kind.equals("line")?"inventory_is_handle":"inventory_status");}
        if(kind.equals("line")){allowed.put("skuSn","sku_sn");allowed.put("batchCode","batch_code");}
        if(!kind.equals("supplier"))allowed.put("storeCode","wms_simulation_code");
        allowed.forEach((key,col)->{if(!text(q.get(key)).isEmpty()){boolean like=key.equals("keyword")||key.equals("companyName");w.append(" AND x.").append(col).append(like?" LIKE ?":"=?");args.add(like?"%"+text(q.get(key))+"%":q.get(key));}});
        String updated=kind.equals("ticket")||kind.equals("line")?"business_updated_time":"modify_time";String begin=text(q.get("beginTime")),end=text(q.get("endTime"));try{if(!begin.isEmpty()){w.append(" AND x."+updated+">=?");args.add(LocalDate.parse(begin).atStartOfDay());}if(!end.isEmpty()){w.append(" AND x."+updated+"<?");args.add(LocalDate.parse(end).plusDays(1).atStartOfDay());}require(begin.isEmpty()||end.isEmpty()||!LocalDate.parse(begin).isAfter(LocalDate.parse(end)),"开始日期不能晚于结束日期");}catch(java.time.format.DateTimeParseException e){throw new IllegalArgumentException("日期格式错误");}return w.toString();
    }
    public TableDataInfo page(String supplied,String kind,Map<String,Object> q,int page,int size){String c=company(supplied);List<Object>a=new ArrayList<>();a.add(c);String sql=" FROM ("+base(kind)+") x WHERE UPPER(x.company_code)=?"+filter(kind,q,a);long total=count("SELECT COUNT(*)"+sql,a.toArray());a.add(Math.max(1,Math.min(size,100)));a.add((long)(Math.max(page,1)-1)*Math.max(1,Math.min(size,100)));TableDataInfo result=new TableDataInfo();result.setCode(200);result.setMsg("查询成功");result.setRows(rows("SELECT x.*"+sql+" ORDER BY x."+(kind.equals("ticket")||kind.equals("line")?"business_updated_time":"modify_time")+" DESC,x.id DESC LIMIT ? OFFSET ?",a.toArray()));result.setTotal(total);return result;}
    public List<Map<String,Object>> exportRows(String supplied,String kind,Map<String,Object> q){List<Object>a=new ArrayList<>();a.add(company(supplied));String sql=" FROM ("+base(kind)+") x WHERE UPPER(x.company_code)=?"+filter(kind,q,a);require(count("SELECT COUNT(*)"+sql,a.toArray())<=10000,"导出最多 10000 行，请缩小筛选范围");return rows("SELECT x.*"+sql+" ORDER BY x."+(kind.equals("ticket")||kind.equals("line")?"business_updated_time":"modify_time")+" DESC,x.id DESC",a.toArray());}
    public Map<String,Object> options(String supplied){String c=company(supplied);return map("suppliers",rows("SELECT id,supplier_sn,supplier_name,status FROM supplier_info WHERE UPPER(company_code)=? ORDER BY supplier_name",c),"warehouses",warehouses.list(c,"simulationStore",Collections.emptyMap()),"regions",rows("SELECT DISTINCT contact_province,contact_city,contact_area FROM supplier_info WHERE UPPER(company_code)=?",c));}
    public Map<String,Object> detail(String supplied,String kind,long key){String c=company(supplied);one(c,kind,key);Map<String,Object> result=rows("SELECT x.* FROM ("+base(kind)+") x WHERE UPPER(x.company_code)=? AND x.id=?",c,key).get(0);String sn=text(result.get(code(kind)));
        result.put("events",rows("SELECT * FROM purchase_event WHERE company_code=? AND document_sn=? ORDER BY id DESC",c,sn));
        if(kind.equals("supplier"))result.put("purchases",rows("SELECT x.* FROM ("+base("purchase")+") x WHERE UPPER(x.company_code)=? AND x.supplier_sn=? ORDER BY x.id DESC",c,sn));
        if(kind.equals("purchase")){result.put("lines",purchaseLines(c,sn));result.put("receipts",rows("SELECT * FROM no_tickets WHERE UPPER(company_code)=? AND po_sn=? ORDER BY id DESC",c,sn));result.put("tickets",rows("SELECT x.* FROM ("+base("ticket")+") x WHERE UPPER(x.company_code)=? AND x.original_sn=? ORDER BY x.id DESC",c,sn));}
        if(kind.equals("receipt")){result.put("lines",rows("SELECT * FROM no_tickets_goods WHERE UPPER(company_code)=? AND no_sn=? ORDER BY id",c,sn));result.put("tickets",rows("SELECT x.* FROM ("+base("ticket")+") x WHERE UPPER(x.company_code)=? AND x.relation_sn=? ORDER BY x.id",c,sn));}
        if(kind.equals("ticket")) {
            result.put("lines",rows("SELECT x.* FROM ("+base("line")+") x WHERE UPPER(x.company_code)=? AND x.sn=? ORDER BY x.id",c,sn));
            result.put("purchaseId",byCode(c,"purchase","po_sn",text(result.get("originalSn"))).get("id"));
            result.put("receiptId",byCode(c,"receipt","no_sn",text(result.get("relationSn"))).get("id"));
        }return result;
    }
    public TableDataInfo receiptBatches(String supplied,long ticketId,int page,int size) {
        String c=company(supplied);Map<String,Object> ticket=one(c,"ticket",ticketId);
        String source=integer(ticket.get("actualWarehouse"))==1?
            "SELECT r.*,g.goods_name,e.message_id,e.final_receipt FROM wms_receipt_line r JOIN wms_inbound_task a ON a.id=r.task_id AND a.company_code=r.company_code JOIN wms_receipt_event e ON e.id=r.event_id AND e.company_code=r.company_code JOIN wms_tickets_goods g ON g.id=r.ticket_line_id AND UPPER(g.company_code)=r.company_code WHERE a.company_code=? AND a.ticket_id=?":
            "SELECT g.id,g.sku_sn,g.goods_name,g.batch_code,g.number_zp good_qty,g.number_cp bad_qty,CASE WHEN g.inventory_is_handle=2 THEN 1 WHEN g.inventory_is_handle=3 THEN 2 ELSE 0 END posted,g.error_info,g.wms_actually_time create_time,'自动虚拟收货' message_id,1 final_receipt FROM wms_tickets_goods g JOIN wms_tickets t ON t.sn=g.sn AND UPPER(t.company_code)=UPPER(g.company_code) WHERE UPPER(t.company_code)=? AND t.id=? AND t.status_ticket=2";
        TableDataInfo result=new TableDataInfo();result.setCode(200);result.setMsg("查询成功");result.setTotal(count("SELECT COUNT(*) FROM ("+source+") x",c,ticketId));
        int limit=Math.max(1,Math.min(size,100));result.setRows(rows("SELECT x.* FROM ("+source+") x ORDER BY x.id DESC LIMIT ? OFFSET ?",c,ticketId,limit,(long)(Math.max(1,page)-1)*limit));return result;
    }
    public List<Map<String,Object>> purchaseLines(String c,String sn){return rows("SELECT l.*,COALESCE((SELECT SUM(CASE WHEN n.no_state=4 THEN g.zp_number_actually+g.cp_number_actually ELSE g.zp_number_expected+g.cp_number_expected END) FROM no_tickets_goods g JOIN no_tickets n ON n.no_sn=g.no_sn AND UPPER(n.company_code)=UPPER(g.company_code) WHERE UPPER(n.company_code)=UPPER(l.company_code) AND n.po_sn=l.po_sn AND n.no_state<>-1 AND g.sku_sn=l.sku_sn),0) scheduled_quantity, COALESCE((SELECT SUM(g.zp_number_actually+g.cp_number_actually) FROM no_tickets_goods g JOIN no_tickets n ON n.no_sn=g.no_sn AND UPPER(n.company_code)=UPPER(g.company_code) WHERE UPPER(n.company_code)=UPPER(l.company_code) AND n.po_sn=l.po_sn AND n.no_state<>-1 AND g.sku_sn=l.sku_sn),0) received_quantity FROM purchase_line l WHERE l.company_code=? AND l.po_sn=? ORDER BY l.id",c,sn);}
    @Transactional(isolation=Isolation.READ_COMMITTED) public long saveSupplier(String supplied,Map<String,Object> input,String user){String c=company(supplied);long key=text(input.get("id")).isEmpty()?0:id(input.get("id"));Map<String,Object> old=key==0?null:lockDocument(c,"supplier",key);String name=required(input,"supplierName","供应商简称",100),full=required(input,"companyName","公司全称",200);int status=integer(input.getOrDefault("status",2));require(status==1||status==2,"请选择启用或停用");require(count("SELECT COUNT(*) FROM supplier_info WHERE UPPER(company_code)=? AND (supplier_name=? OR company_name=?) AND id<>?",c,name,full,key)==0,"供应商简称或公司全称已存在");String phone=text(input.get("contactTel"));require(phone.isEmpty()||phone.matches("[0-9+()\\- #]{3,40}"),"请输入有效联系电话");Map<String,Object> fields=map("supplier_name",name,"company_name",full,"status",status,"contact_user",text(input.get("contactUser")),"contact_tel",phone,"contact_province",text(input.get("contactProvince")),"contact_city",text(input.get("contactCity")),"contact_area",text(input.get("contactArea")),"contact_address",text(input.get("contactAddress")),"peration_user",user);
        for(Object v:fields.values())require(text(v).length()<=255,"资料字段不能超过 255 字");
        if(old==null){fields.put("supplier_sn",sn("SUP"));fields.put("company_code",c);key=insert("supplier_info",fields);}else{if(input.containsKey("supplierSn"))require(text(old.get("supplierSn")).equals(text(input.get("supplierSn"))),"供应商编码不能修改");List<Object>a=new ArrayList<>(fields.values());a.add(key);a.add(c);jdbc.update("UPDATE supplier_info SET "+fields.keySet().stream().map(k->k+"=?").collect(Collectors.joining(","))+" WHERE id=? AND UPPER(company_code)=?",a.toArray());}event(c,text(lockDocument(c,"supplier",key).get("supplierSn")),old==null?"创建供应商":"修改供应商",user,status==2?"启用":"停用");return key;}
    @Transactional(isolation=Isolation.READ_COMMITTED) public void deleteSupplier(String supplied,long key,String user){String c=company(supplied);Map<String,Object> row=lockDocument(c,"supplier",key);String sn=text(row.get("supplierSn"));require(count("SELECT COUNT(*) FROM po_info WHERE UPPER(company_code)=? AND supplier_sn=?",c,sn)==0,"供应商已有采购单引用（含草稿、已完成、已作废），不能删除，请停用");jdbc.update("DELETE FROM supplier_info WHERE id=? AND UPPER(company_code)=?",key,c);event(c,sn,"删除供应商",user,"删除未使用供应商");}
    @SuppressWarnings("unchecked") private List<Map<String,Object>> inputLines(Map<String,Object> input){Object raw=input.get("lines");require(raw instanceof List,"请添加商品明细");List<Map<String,Object>> list=(List<Map<String,Object>>)raw;require(!list.isEmpty()&&list.size()<=200,"每单必须包含 1 至 200 行商品");return list;}
    public List<Map<String,Object>> validateLines(String supplied,List<Map<String,Object>> lines){String c=company(supplied);require(!lines.isEmpty()&&lines.size()<=200,"每单必须包含 1 至 200 行商品");Set<String> seen=new HashSet<>();List<Map<String,Object>> out=new ArrayList<>();for(int i=0;i<lines.size();i++){Map<String,Object> row=lines.get(i);try{String sku=required(row,"skuSn","SKU",100);require(seen.add(sku),"SKU 重复："+sku);int qty=integer(row.get("quantity"));require(qty>0&&qty<=100000000,"采购数量须为 1 至 100000000 的整数");BigDecimal price=money(row.get("purchasePrice"));GoodsSkuSnInfo query=new GoodsSkuSnInfo();query.setSkuSn(sku);R<GoodsSkuSnInfo> response=goods.lookup(query,c,com.ruoyi.common.core.constant.SecurityConstants.INNER);require(response!=null&&R.isSuccess(response),"商品服务暂不可用，请重试");GoodsSkuSnInfo found=response.getData();require(found!=null&&sku.equals(found.getSkuSn()),"商品不存在："+sku);out.add(map("skuSn",sku,"goodsName",found.getGoodsName(),"goodsSn",found.getGoodsSn(),"barcodeSn",found.getBarcodeSn(),"quantity",qty,"purchasePrice",price));}catch(IllegalArgumentException e){throw new IllegalArgumentException("第 "+(i+1)+" 行："+e.getMessage());}}return out;}
    @Transactional(isolation=Isolation.READ_COMMITTED) public long savePurchase(String supplied,Map<String,Object> input,String user){String c=company(supplied);List<Map<String,Object>> lines=validateLines(c,inputLines(input));long key=text(input.get("id")).isEmpty()?0:id(input.get("id"));Map<String,Object> old=key==0?null:lockDocument(c,"purchase",key);if(old!=null){require(integer(old.get("poState"))==1,"仅草稿采购单可以修改");require(count("SELECT COUNT(*) FROM no_tickets WHERE UPPER(company_code)=? AND po_sn=?",c,old.get("poSn"))==0,"已有到货单，不能重写采购计划");}
        String name=required(input,"poName","采购名称",100),supplier=required(input,"supplierSn","供应商",255),store=required(input,"wmsSimulationCode","收货虚仓",100);Map<String,Object>s=supplierForReference(c,supplier);require(integer(s.get("status"))==2,"供应商已停用");SimulationStoreInfoDto warehouse=warehouses.resolve(c,store,true);int quantity=0;BigDecimal total=BigDecimal.ZERO;for(Map<String,Object> line:lines){quantity=Math.addExact(quantity,integer(line.get("quantity")));total=total.add(money(line.get("purchasePrice")).multiply(BigDecimal.valueOf(integer(line.get("quantity")))));}require(total.precision()<=15,"采购总金额超过系统上限");String date=text(input.get("expectedDate"));if(!date.isEmpty())try{LocalDate.parse(date);}catch(Exception e){throw new IllegalArgumentException("预计到货日期格式错误");}String remarks=text(input.get("remarks"));require(remarks.length()<=2000,"备注不能超过 2000 字");String sn=old==null?sn("PO"):text(old.get("poSn"));if(old==null)key=insert("po_info",map("po_sn",sn,"po_name",name,"supplier_sn",supplier,"department_code","","wms_simulation_code",store,"actual_warehouse",warehouse.getInboundMode(),"company_code",c));
        jdbc.update("UPDATE po_info SET po_name=?,supplier_sn=?,wms_simulation_code=?,actual_warehouse=?,number_expected=?,money_expected=?,expected_date=?,remarks=?,peration_user=? WHERE id=? AND UPPER(company_code)=?",name,supplier,store,warehouse.getInboundMode(),quantity,total,date.isEmpty()?null:date,remarks,user,key,c);jdbc.update("DELETE FROM purchase_line WHERE company_code=? AND po_sn=?",c,sn);for(Map<String,Object> l:lines)insert("purchase_line",map("company_code",c,"po_sn",sn,"sku_sn",l.get("skuSn"),"goods_name",l.get("goodsName"),"goods_sn",l.get("goodsSn"),"barcode_sn",l.get("barcodeSn"),"quantity",l.get("quantity"),"purchase_price",l.get("purchasePrice")));event(c,sn,old==null?"创建采购":"修改采购",user,"计划数量 "+quantity+"，计划金额 "+total);return key;}
    @Transactional(isolation=Isolation.READ_COMMITTED) public void approve(String supplied,long key,String user){String c=company(supplied);Map<String,Object> p=lockDocument(c,"purchase",key);require(integer(p.get("poState"))==1,"采购单已审核或状态不允许审核");require(count("SELECT COUNT(*) FROM no_tickets WHERE UPPER(company_code)=? AND po_sn=?",c,p.get("poSn"))==0,"草稿已关联到货单，请先核对单据状态，不能重复审核");require(integer(supplierForReference(c,text(p.get("supplierSn"))).get("status"))==2,"供应商已停用");warehouses.resolve(c,text(p.get("wmsSimulationCode")),true);require(!purchaseLines(c,text(p.get("poSn"))).isEmpty(),"采购商品不能为空");jdbc.update("UPDATE po_info SET po_state=2 WHERE id=? AND UPPER(company_code)=?",key,c);event(c,text(p.get("poSn")),"审核采购",user,"采购计划已锁定，可以分批创建到货单");}
    @Transactional(isolation=Isolation.READ_COMMITTED) public long createReceipt(String supplied,long purchaseId,Map<String,Object> input,String user){String c=company(supplied);Map<String,Object> p=lockDocument(c,"purchase",purchaseId);require(Arrays.asList(2,3).contains(integer(p.get("poState"))),"仅待收货或收货中的采购单可以创建到货单");warehouses.resolve(c,text(p.get("wmsSimulationCode")),true);Map<Long,Map<String,Object>> plan=new HashMap<>();for(Map<String,Object> l:purchaseLines(c,text(p.get("poSn"))))plan.put(id(l.get("id")),l);Set<Long> seen=new HashSet<>();List<Map<String,Object>> selected=inputLines(input);int total=0;BigDecimal amount=BigDecimal.ZERO;for(Map<String,Object> l:selected){long lineId=id(l.get("lineId"));require(seen.add(lineId)&&plan.containsKey(lineId),"采购明细不存在或重复");int qty=integer(l.get("quantity"));Map<String,Object> pl=plan.get(lineId);require(qty>0&&qty<=integer(pl.get("quantity"))-integer(pl.get("scheduledQuantity")),"SKU "+pl.get("skuSn")+" 超过剩余可安排到货数量");total=Math.addExact(total,qty);amount=amount.add(money(pl.get("purchasePrice")).multiply(BigDecimal.valueOf(qty)));}
        String expected=text(input.getOrDefault("expectedDate",p.get("expectedDate")));if(!expected.isEmpty())try{LocalDate.parse(expected);}catch(Exception e){throw new IllegalArgumentException("预计到货日期格式错误");}String remarks=text(input.get("remarks"));require(remarks.length()<=255,"到货备注不能超过 255 字");String sn=sn("NO_"),batch=sn("B");long key=insert("no_tickets",map("no_sn",sn,"po_sn",p.get("poSn"),"no_name",p.get("poName"),"wms_simulation_code",p.get("wmsSimulationCode"),"batch_code",batch,"expected_callback_time",expected.isEmpty()?null:expected,"remarks",remarks,"no_state",2,"number_expected",total,"price_expected",amount,"company_code",c,"created_user",user));for(Map<String,Object> l:selected){Map<String,Object> pl=plan.get(id(l.get("lineId")));insert("no_tickets_goods",map("no_sn",sn,"sku_sn",pl.get("skuSn"),"goods_sn",pl.get("goodsSn"),"goods_name",pl.get("goodsName"),"barcode_sn",pl.get("barcodeSn"),"purchase_price",pl.get("purchasePrice"),"zp_number_expected",integer(l.get("quantity")),"company_code",c));}event(c,sn,"创建到货单",user,"待审核，计划到货 "+total);event(c,text(p.get("poSn")),"分批到货",user,"创建 "+sn+"，数量 "+total);return key;}
    /** Commit the execution document before calling inventory so a retry always reuses its key. */
    @Transactional(propagation=org.springframework.transaction.annotation.Propagation.NOT_SUPPORTED)
    public long approveReceipt(String supplied,long key,String user){
        long ticketId=transaction().execute(status->prepareReceipt(supplied,key,user));
        Map<String,Object> ticket=one(company(supplied),"ticket",ticketId);
        if(integer(ticket.get("actualWarehouse"))==2)completeVirtual(supplied,ticketId,user);
        return ticketId;
    }
    @Transactional(propagation=org.springframework.transaction.annotation.Propagation.NOT_SUPPORTED) public boolean completeVirtual(String supplied,long key,String user){
        // Also called from approveReceipt after its first transaction has fully committed.
        transaction().execute(status->{
            String c=company(supplied);Map<String,Object> t=lockDocument(c,"ticket",key);
            require(integer(t.get("actualWarehouse"))==2&&integer(t.get("ticketType"))==1,"仅虚拟入库单可自动完成入库");
            require(Arrays.asList(0,2,3).contains(integer(t.get("inventoryStatus"))),"当前库存入账状态不允许执行");
            require(Arrays.asList(1,2).contains(integer(t.get("statusTicket"))),"当前入库单状态不允许自动入库");
            if(integer(t.get("statusTicket"))==1){
                warehouses.resolve(c,text(t.get("wmsSimulationCode")),true);
                Map<String,Object> receipt=byCode(c,"receipt","no_sn",text(t.get("relationSn")));
                require(integer(receipt.get("noState"))==3,"仅已审核待入库到货单可以自动收货");
                List<Map<String,Object>> quantities=new ArrayList<>();
                for(Map<String,Object> l:rows("SELECT * FROM wms_tickets_goods WHERE UPPER(company_code)=? AND sn=? ORDER BY id",c,t.get("sn")))quantities.add(map("id",l.get("id"),"numberZp",l.get("numberExpected"),"numberCp",0));
                receive(c,key,map("lines",quantities),user);
                event(c,text(t.get("sn")),"自动虚拟收货",user,"按已审核到货计划全量收货，自动进行库存入账");
            }
            return null;
        });
        return transaction().execute(status->postInventory(supplied,key,user));
    }
    private long prepareReceipt(String supplied,long key,String user){String c=company(supplied);Map<String,Object> n=lockDocument(c,"receipt",key);require(integer(n.get("noState"))==2,"仅待审核到货单可以审核");Map<String,Object> p=byCode(c,"purchase","po_sn",text(n.get("poSn")));require(Arrays.asList(2,3).contains(integer(p.get("poState"))),"采购单已关闭或作废");require(text(p.get("wmsSimulationCode")).equals(text(n.get("wmsSimulationCode"))),"到货仓库与采购单不一致");SimulationStoreInfoDto warehouse=warehouses.resolve(c,text(n.get("wmsSimulationCode")),true);require(count("SELECT COUNT(*) FROM wms_tickets WHERE UPPER(company_code)=? AND relation_sn=?",c,n.get("noSn"))==0,"到货单已生成入库执行单");List<Map<String,Object>> lines=rows("SELECT * FROM no_tickets_goods WHERE UPPER(company_code)=? AND no_sn=?",c,n.get("noSn"));require(!lines.isEmpty(),"到货商品不能为空");String sn=sn("CG_");long ticketId=insert("wms_tickets",map("sn",sn,"ticket_type",1,"relation_sn",n.get("noSn"),"original_sn",n.get("poSn"),"wms_simulation_code",n.get("wmsSimulationCode"),"wms_simulation_name",warehouse.getWmsSimulationName(),"real_store_code",warehouse.getOwnerInfo().getRealStoreCode(),"customer_no",warehouse.getExternalOwner(),"store_type",warehouse.getOwnerInfo().getRealStoreInfo().getWmsType(),"actual_warehouse",warehouse.getInboundMode(),"company_code",c,"user_name",user,"status_ticket",1));for(Map<String,Object> l:lines)insert("wms_tickets_goods",map("sn",sn,"inventory_type","ZP","sku_sn",l.get("skuSn"),"goods_sn",l.get("goodsSn"),"goods_name",l.get("goodsName"),"barcode_sn",l.get("barcodeSn"),"batch_code",n.get("batchCode"),"purchase_price",l.get("purchasePrice"),"number_expected",l.get("zpNumberExpected"),"company_code",c));jdbc.update("UPDATE no_tickets SET no_state=3,relation_sn=?,reviewer_user=?,reviewer_time=NOW() WHERE id=? AND UPPER(company_code)=?",sn,user,key,c);event(c,text(n.get("noSn")),"审核到货单",user,"生成入库执行单 "+sn);event(c,sn,"创建入库执行单",user,integer(warehouse.getInboundMode())==2?"虚拟入库：审核后自动收货并入账":"真实入库：等待仓库回传；已创建待下发任务");if(warehouse.getInboundMode()==1)wms.prepare(c,ticketId,warehouse);return ticketId;}
    @Transactional(isolation=Isolation.READ_COMMITTED) public void receive(String supplied,long key,Map<String,Object> input,String user){String c=company(supplied);Map<String,Object> t=lockDocument(c,"ticket",key);require(integer(t.get("actualWarehouse"))==2,"真实仓库需由 WMS 回传确认，不能人工模拟入库");require(integer(t.get("ticketType"))==1&&integer(t.get("statusTicket"))==1,"仅待执行入库单可确认收货");List<Map<String,Object>> stored=rows("SELECT * FROM wms_tickets_goods WHERE UPPER(company_code)=? AND sn=?",c,t.get("sn"));List<Map<String,Object>> received=inputLines(input);require(stored.size()==received.size(),"请提交全部商品的实收数量");Map<Long,Map<String,Object>> indexes=new HashMap<>();for(Map<String,Object> l:stored)indexes.put(id(l.get("id")),l);Set<Long> seen=new HashSet<>();for(Map<String,Object> l:received){long lineId=id(l.get("id"));require(seen.add(lineId)&&indexes.containsKey(lineId),"商品明细重复或不属于该单据");int zp=integer(l.get("numberZp")),cp=integer(l.get("numberCp"));require(zp>=0&&cp>=0&&(long)zp+cp<=integer(indexes.get(lineId).get("numberExpected")),"实收数量不能为负数或超过计划数量");jdbc.update("UPDATE wms_tickets_goods SET number_zp=?,number_cp=?,number_actually=?,number_dif_actually=number_expected-?,wms_actually_time=CURDATE() WHERE id=? AND UPPER(company_code)=?",zp,cp,zp+cp,zp+cp,lineId,c);}jdbc.update("UPDATE wms_tickets SET status_ticket=2,wms_actually_time=CURDATE(),accept_callback_time=CURDATE() WHERE id=? AND UPPER(company_code)=?",key,c);refreshPurchase(c,text(t.get("originalSn")));event(c,text(t.get("sn")),"确认收货",user,"已记录实收正品、次品，等待库存入账");}
    /** Retry is safe after a network timeout or local rollback: inventory deduplicates by company/SKU/document/batch/store. */
    @Transactional(isolation=Isolation.READ_COMMITTED) public boolean postInventory(String supplied,long key,String user){String c=company(supplied);Map<String,Object> t=lockDocument(c,"ticket",key);if(integer(t.get("actualWarehouse"))==1)return wms.post(c,key);require(integer(t.get("ticketType"))==1&&integer(t.get("statusTicket"))==2,"仓库尚未确认入库，不能入账");if(integer(t.get("inventoryStatus"))==2)return true;require(Arrays.asList(0,3).contains(integer(t.get("inventoryStatus"))),"当前库存入账状态不允许执行");List<Map<String,Object>> lines=rows("SELECT * FROM wms_tickets_goods WHERE UPPER(company_code)=? AND sn=? ORDER BY id",c,t.get("sn"));require(!lines.isEmpty(),"入库商品不能为空");boolean complete=true;for(Map<String,Object> l:lines){if(integer(l.get("inventoryIsHandle"))==2)continue;String error=null;try{int zp=integer(l.get("numberZp")),cp=integer(l.get("numberCp"));if(zp+cp>0){WmsInventoryBatch batch=new WmsInventoryBatch();batch.setCompanyCode(c);batch.setStoreCode(text(t.get("wmsSimulationCode")));batch.setSkuSn(text(l.get("skuSn")));batch.setBatchCode(text(l.get("batchCode")));batch.setZpActualNumber(zp);batch.setZpAvailableNumber(zp);batch.setCpActualNumber(cp);batch.setCpAvailableNumber(cp);batch.setTransactionPrice(money(l.get("purchasePrice")));WmsInventoryBatchDto dto=new WmsInventoryBatchDto();dto.setRelationSn(text(t.get("sn")));dto.setWmsInventoryBatch(batch);R<Boolean> r=inventory.addInventory(dto,c);require(r!=null&&R.isSuccess(r)&&!Boolean.FALSE.equals(r.getData()),r==null?"库存服务无响应":text(r.getMsg()));}}catch(Exception e){complete=false;error=text(e.getMessage());if(error.isEmpty())error="库存服务异常，请重试";}
            jdbc.update("UPDATE wms_tickets_goods SET inventory_is_handle=?,error_info=? WHERE id=? AND UPPER(company_code)=?",error==null?2:3,error==null?null:error.substring(0,Math.min(error.length(),500)),l.get("id"),c);
        }jdbc.update("UPDATE wms_tickets SET inventory_status=? WHERE id=? AND UPPER(company_code)=?",complete?2:3,key,c);syncReceipt(c,t,complete);event(c,text(t.get("sn")),complete?"库存入账成功":"库存入账异常",user,complete?"全部商品入账完成":"部分商品未入账，请查看明细失败原因并重试");return complete;}
    private void syncReceipt(String c,Map<String,Object> ticket,boolean complete){Map<String,Object> n=byCode(c,"receipt","no_sn",text(ticket.get("relationSn")));jdbc.update("UPDATE no_tickets_goods n JOIN wms_tickets_goods g ON g.sku_sn=n.sku_sn AND UPPER(g.company_code)=UPPER(n.company_code) SET n.zp_number_actually=CASE WHEN g.inventory_is_handle=2 THEN g.number_zp ELSE 0 END,n.cp_number_actually=CASE WHEN g.inventory_is_handle=2 THEN g.number_cp ELSE 0 END WHERE UPPER(n.company_code)=? AND n.no_sn=? AND g.sn=?",c,n.get("noSn"),ticket.get("sn"));refreshWmsReceipt(c,ticket,complete);}
    public void refreshWmsReceipt(String c,Map<String,Object> ticket,boolean complete){Map<String,Object> n=byCode(c,"receipt","no_sn",text(ticket.get("relationSn")));Map<String,Object> totals=rows("SELECT COALESCE(SUM(zp_number_actually+cp_number_actually),0) qty,COALESCE(SUM((zp_number_actually+cp_number_actually)*purchase_price),0) amount FROM no_tickets_goods WHERE UPPER(company_code)=? AND no_sn=?",c,n.get("noSn")).get(0);jdbc.update("UPDATE no_tickets SET no_state=?,number_actually=?,price_actually=?,actually_callback_time=CASE WHEN ? THEN NOW() ELSE actually_callback_time END WHERE id=? AND UPPER(company_code)=?",complete?4:3,totals.get("qty"),totals.get("amount"),complete,n.get("id"),c);refreshPurchase(c,text(n.get("poSn")));}
    private void refreshPurchase(String c,String poSn){Map<String,Object> sum=rows("SELECT COALESCE(SUM(number_actually),0) qty,COALESCE(SUM(price_actually),0) amount FROM no_tickets WHERE UPPER(company_code)=? AND po_sn=? AND no_state<>-1",c,poSn).get(0);jdbc.update("UPDATE po_info SET number_actually=?,money_actually=?,po_state=CASE WHEN po_state IN(-1,5) THEN po_state WHEN number_expected>0 AND ? >= number_expected THEN 4 WHEN ?>0 OR EXISTS(SELECT 1 FROM wms_tickets t JOIN wms_tickets_goods g ON g.sn=t.sn AND UPPER(g.company_code)=UPPER(t.company_code) WHERE UPPER(t.company_code)=UPPER(po_info.company_code) AND t.original_sn=po_info.po_sn AND t.status_ticket=2 AND g.number_actually>0) THEN 3 ELSE 2 END WHERE UPPER(company_code)=? AND po_sn=?",sum.get("qty"),sum.get("amount"),sum.get("qty"),sum.get("qty"),c,poSn);}
    @Transactional(isolation=Isolation.READ_COMMITTED) public void cancel(String supplied,String kind,long key,String reason,String user){String c=company(supplied);require(!text(reason).isEmpty()&&reason.length()<=500,"请填写作废原因，最多 500 字");Map<String,Object> row=lockDocument(c,kind,key);String sn=text(row.get(code(kind)));
        if(kind.equals("purchase")){require(integer(row.get("poState"))==1||integer(row.get("poState"))==2,"收货中或已结束采购单不能作废");require(count("SELECT COUNT(*) FROM no_tickets WHERE UPPER(company_code)=? AND po_sn=? AND no_state<>-1",c,sn)==0,"请先处理有效到货单");jdbc.update("UPDATE po_info SET po_state=-1,close_reason=? WHERE id=? AND UPPER(company_code)=?",reason,key,c);}
        else if(kind.equals("receipt")){require(Arrays.asList(1,2).contains(integer(row.get("noState"))),"已生成执行单，请从出入库单申请作废");jdbc.update("UPDATE no_tickets SET no_state=-1 WHERE id=? AND UPPER(company_code)=?",key,c);}
        else if(kind.equals("ticket")){require(integer(row.get("actualWarehouse"))==2,"真实入库单请使用仓库取消操作");require(integer(row.get("statusTicket"))<=1&&integer(row.get("statusNotify"))==0&&integer(row.get("inventoryStatus"))==0,"已通知仓库、已执行或已入账单据不能直接作废");require(count("SELECT COUNT(*) FROM wms_tickets_goods WHERE UPPER(company_code)=? AND sn=? AND (inventory_is_handle<>0 OR number_actually<>0)",c,sn)==0,"单据已有收货或库存处理记录，不能作废");jdbc.update("UPDATE wms_tickets SET status_ticket=5,time_cancel=CURDATE() WHERE id=? AND UPPER(company_code)=?",key,c);jdbc.update("UPDATE no_tickets SET no_state=-1 WHERE UPPER(company_code)=? AND no_sn=?",c,row.get("relationSn"));event(c,text(row.get("relationSn")),"作废到货单",user,reason);}
        else throw new IllegalArgumentException("该类型不支持作废");event(c,sn,"作废",user,reason);}
    @Transactional(isolation=Isolation.READ_COMMITTED) public void closePurchase(String supplied,long key,String reason,String user){String c=company(supplied);Map<String,Object> p=lockDocument(c,"purchase",key);require(Arrays.asList(2,3).contains(integer(p.get("poState"))),"仅未完成采购单可以关闭剩余数量");require(!text(reason).isEmpty()&&reason.length()<=500,"请填写关闭原因，最多 500 字");require(count("SELECT COUNT(*) FROM no_tickets WHERE UPPER(company_code)=? AND po_sn=? AND no_state NOT IN(-1,4)",c,p.get("poSn"))==0,"请先完成或作废所有在途到货单");jdbc.update("UPDATE po_info SET po_state=5,close_reason=? WHERE id=? AND UPPER(company_code)=?",reason,key,c);event(c,text(p.get("poSn")),"关闭剩余采购",user,reason);}
    public Map<String,Object> lockWmsTicket(String c,long id){
        require(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive(),"仓库执行需在事务内锁定单据");
        Map<String,Object> t=lockDocument(company(c),"ticket",id);require(integer(t.get("actualWarehouse"))==1,"仅真实入库单允许仓库回传");return t;
    }
    public void recordWmsEvent(String c,String sn,String action,String message){event(c,sn,action,"WMS",message);}

}
