"""Remove only uniquely prefixed purchase UI fixtures after acceptance."""
import re
import sys
from local_db import execute, quote

def cleanup(prefix):
    assert re.fullmatch(r'PURUI[0-9]{10}', prefix), 'Exact generated UI fixture prefix required'
    pattern = quote(prefix+'%')
    db = 'qm_oms_saas_commodity'
    # Purchase names and supplier names are generated by the acceptance script, never business names.
    po = "SELECT po_sn FROM po_info WHERE po_name LIKE "+pattern
    no = "SELECT no_sn FROM no_tickets WHERE po_sn IN ("+po+")"
    ticket = "SELECT sn FROM wms_tickets WHERE original_sn IN ("+po+")"
    statements = [
        f'DELETE FROM purchase_event WHERE document_sn IN ({po}) OR document_sn IN ({no}) OR document_sn IN ({ticket}) OR document_sn IN (SELECT supplier_sn FROM supplier_info WHERE supplier_name LIKE {pattern})',
        f'DELETE FROM wms_tickets_goods WHERE sn IN ({ticket})',
        f'DELETE FROM no_tickets_goods WHERE no_sn IN ({no})',
        f'DELETE FROM wms_tickets WHERE original_sn IN ({po})',
        f'DELETE FROM no_tickets WHERE po_sn IN ({po})',
        f'DELETE FROM purchase_line WHERE po_sn IN ({po})',
        f'DELETE FROM po_info WHERE po_name LIKE {pattern}',
        f'DELETE FROM supplier_info WHERE supplier_name LIKE {pattern}',
    ]
    execute('START TRANSACTION;'+ ';'.join(statements)+';COMMIT;', db)
    execute('START TRANSACTION;'+';'.join(f'DELETE FROM {t} WHERE sku_sn LIKE {pattern}' for t in ['wms_inventory_change_history','wms_inventory_batch','wms_inventory','oms_inventory'])+';COMMIT;', 'qm_oms_saas_inventory')
    execute('START TRANSACTION;'+';'.join([
        f'DELETE FROM goods_sku_sn_info WHERE sku_sn LIKE {pattern}',
        f'DELETE FROM wms_simulation_store_info WHERE wms_simulation_code LIKE {pattern}',
        f'DELETE FROM owner_warehouse WHERE owner_id IN (SELECT id FROM owner_info WHERE owner_code LIKE {pattern})',
        f'DELETE FROM owner_info WHERE owner_code LIKE {pattern}',
        f'DELETE FROM wms_real_store_info WHERE real_store_code LIKE {pattern}',
    ])+';COMMIT;', db)
    print('Cleaned temporary purchase fixtures:', prefix)

if __name__ == '__main__': cleanup(sys.argv[1])
