worker_processes auto;
events { worker_connections 1024; }
http {
include /etc/nginx/mime.types;
default_type application/octet-stream;
sendfile on;
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    client_max_body_size 50m;
    location = /channel-authorize {
        access_log off;
        add_header Referrer-Policy no-referrer always;
        add_header Cache-Control no-store always;
        try_files /index.html =404;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~ /actuator {
        return 403;
    }
    location /prod-api/ {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $gateway http://gateway:8080;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite ^/prod-api/(.*)$ /$1 break;
        proxy_pass $gateway;
    }
}
}
