<template>
  <el-dialog title="仓库交互日志" :visible.sync="visible" width="1100px" append-to-body :close-on-click-modal="false">
    <el-form inline size="small" @submit.native.prevent="search"><el-form-item label="入库执行单号"><el-input v-model.trim="sn" clearable placeholder="输入完整执行单号" @keyup.enter.native="search" /></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="load">刷新</el-button></el-form-item></el-form>
    <el-table v-loading="loading" :data="rows" max-height="450"><el-table-column label="时间" prop="create_time" min-width="155" /><el-table-column label="平台 / 配置" min-width="160"><template slot-scope="s">{{ s.row.provider === 'QIMEN' ? '奇门' : '京东虎符' }} / {{ s.row.connection_name }}</template></el-table-column><el-table-column label="单号" prop="ticket_sn" min-width="225" show-overflow-tooltip /><el-table-column label="动作" width="90"><template slot-scope="s">{{ actions[s.row.action] }}</template></el-table-column><el-table-column label="方向" width="80"><template slot-scope="s">{{ s.row.direction === 'IN' ? '仓库回传' : '请求仓库' }}</template></el-table-column><el-table-column label="结果" width="100"><template slot-scope="s">{{ results[s.row.result] }}</template></el-table-column><el-table-column label="耗时(ms)" prop="duration_ms" width="90" /><el-table-column label="原因" prop="error_info" min-width="180" show-overflow-tooltip /><el-table-column label="操作" width="90" fixed="right"><template slot-scope="s"><el-button v-hasPermi="['warehouse:wms:payload']" type="text" @click="show(s.row)">查看报文</el-button></template></el-table-column></el-table>
    <div class="log-pages"><el-button size="small" :disabled="page === 1 || loading" @click="page--; load()">上一页</el-button><span>第 {{ page }} 页</span><el-button size="small" :disabled="rows.length < 50 || loading" @click="page++; load()">下一页</el-button></div>
    <div slot="footer"><el-button @click="visible = false">关闭</el-button></div>
    <el-dialog title="交互报文（已脱敏）" :visible.sync="payloadVisible" width="850px" append-to-body><template v-if="payload"><p>请求编号：{{ payload.request_id }}</p><p>请求报文</p><pre>{{ payload.request_body }}</pre><p>响应报文</p><pre>{{ payload.response_body || '尚无响应' }}</pre><p>{{ payload.error_info }}</p></template><div slot="footer"><el-button @click="payloadVisible = false">关闭</el-button></div></el-dialog>
  </el-dialog>
</template>
<script>
import { interactionLogs, interactionLog } from '@/api/warehouse/integration'
export default { data() { return { visible: false, loading: false, rows: [], page: 1, sn: '', payloadVisible: false, payload: null, sequence: 0, actions: { CREATE: '下发入库', QUERY: '查询结果', CANCEL: '申请取消', RECEIPT: '收货回传' }, results: { STARTED: '交互中', SUCCESS: '成功', FAILED: '失败', UNKNOWN: '结果待确认' } } }, methods: { open(sn = '') { this.sn = sn; this.page = 1; this.visible = true; this.load() }, search() { this.page = 1; this.load() }, async load() { const seq = ++this.sequence; this.loading = true; try { const r = await interactionLogs({ sn: this.sn, page: this.page }); if (seq === this.sequence) this.rows = r.data } finally { if (seq === this.sequence) this.loading = false } }, async show(row) { this.payload = (await interactionLog(row.id)).data; this.payloadVisible = true } } }
</script>
<style scoped>.log-pages{display:flex;justify-content:flex-end;align-items:center;gap:12px;margin-top:16px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:270px;overflow:auto;padding:12px;background:#f5f7fa}</style>
